#ifndef TRIGGERS_H
#define TRIGGERS_H

#define TRIGGER__IGN_ON 1
#define TRIGGER__IGN_OFF 2
#define TRIGGER__WAIT_BEFORE_SHUTDOWN 3
#define TRIGGER__NOT_RUNNING 4
#define TRIGGER__NOT_POWERED 5

#endif
